include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude: ["**/*.g.dart", "**/*.config.dart", "**/*.freezed.dart", "**/*.gr.dart", "**/*.mocks.dart", "**/*.chopper.dart",]
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    avoid_function_literals_in_foreach_calls: ignore
    avoid_escaping_inner_quotes: ignore
    prefer_constructors_over_static_methods: ignore
    invalid_annotation_target: ignore

dart_code_metrics:
  metrics-exclude:
    - test/**
  rules-exclude:
    - test/**
  metrics:
    cyclomatic-complexity: 20
    maintainability-index: 50
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 80